# Generated by Django 5.0.6 on 2024-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cadastral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cadastral_number",
                    models.CharField(max_length=255, verbose_name="Кадастровый номер"),
                ),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                ("result", models.BooleanField(verbose_name="Результат")),
                (
                    "query_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время отправки запроса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кадастровая информация",
                "verbose_name_plural": "Кадастровая информация",
            },
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="query_time",
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="result",
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="query_data",
            field=models.JSONField(null=True, verbose_name="Данные запроса"),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="query_date",
            field=models.DateTimeField(
                default="2024-06-08T12:38:28.416976", verbose_name="Дата запроса"
            ),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="response_data",
            field=models.JSONField(null=True, verbose_name="Данные ответа"),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="response_status",
            field=models.BooleanField(null=True, verbose_name="Статус ответа"),
        ),
        migrations.AlterField(
            model_name="queryhistory",
            name="cadastral_number",
            field=models.CharField(max_length=100, verbose_name="Кадастровый номер"),
        ),
    ]
